### ISSUE TITLE
Missing advanced functions on GP26, 27, & 28

### ISSUE THREAD

**Issue by ZodiusInfuser** [pinout-xyz/pico.pinout.xyz#14]
These pins have SPI functionality that the advanced view does not show.

![image](https://user-images.githubusercontent.com/7437269/222700652-1091a3d8-4c4e-496c-a29c-b2680724f6df.png)

Is this an easy enough thing for me to edit and raise a PR for? Looks like they would need a 5th column on the UI, so perhaps beyond me web skills?

**Comment by Gadgetoid** [comment]
Whew, that's a rather awkward problem. I might have to eschew the original pinout diagram layout in order to better incorporate the ADC functions.

I guess `Ground / AGround` is rather redundant, and `ADC_VREF1` being moved one spot over is also slightly weird.

What if ADCn was combined with `GPn` in the first label, recoloured to ADC colour and SPI got its rightful slot.

Like this:

![image](https://user-images.githubusercontent.com/1746967/222709238-286ed4c5-33ca-46cc-8180-20825cce5944.png)

**Comment by ZodiusInfuser** [comment]
That compacting seems okay to me, but then I'm not the primary audience of the non-advanced mode.

**Comment by Gadgetoid** [comment]
I don't like the compacting much, but I think it's a necessary evil to avoid occluding pin functions.

All the I2C, SPI and UART RX/TX that's currently not shown by default can be added and make the default view a little more visually balanced :laughing:

**Comment by lurch** [comment]
Works for me :wink:

**Comment by Gadgetoid** [comment]
Proposed default view:

![image](https://user-images.githubusercontent.com/1746967/222718434-4c2ff592-e8ee-442d-931e-0855040e27ce.png)

The "ADC" toggle becomes redundant... well I say "becomes", it was never all that useful.

Still need to address #13

**Comment by ZodiusInfuser** [comment]
Could be argued that those new additional SPI pins should not appear in the default view, since they're not complete blocks? Or at least the one on pin 29? If it were to stay, then the I2C0 SDA and UART0 TX on GP28 should be shown in the default view too 🤔 . Doing that would then mean the advance just adds the CTS, RTS and PWMs.

The addition of the UART on GP20 and GP21 is good. Can't see a reason that would have been excluded on the default.

**Comment by Gadgetoid** [comment]
Ugh, darn CSS changes are being stubborn about re-loading. Might need a cache-buster. Almost as frustrating to refresh as 7-colour e-Ink :skull:
